service:
  name: fis-projects

custom:
  prefix: fis-projects
  webpackIncludeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  profile: default
  memorySize: 512
  deploymentBucket:
    name: com.senacor.${self:provider.region}.serverless-deploys
    serverSideEncryption: AES256
  versionFunctions: false # Optional function versioning
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/fisProjects"

functions:
  newProject:
    handler: newProject.handler
    events:
      - http:
          method: post
          path: projects
          cors: true
  getProject:
    handler: getProject.handler
    events:
      - http:
          method: get
          path: projects/{proxy+}
          cors: true
  getProjects:
    handler: getProjects.handler
    events:
      - http:
          method: get
          path: projects
          cors: true
  deleteProject:
      handler: deleteProject.handler
      events:
        - http:
            method: delete
            path: projects/{proxy+}
            cors: true

resources:
  Resources:
    fisProjects:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: fisProjects
        AttributeDefinitions:
          - AttributeName: projectCode
            AttributeType: S
        KeySchema:
          - AttributeName: projectCode
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
